config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :authentication, path: "", as: "" do
    resources :users, only: %i[new create], path: "/register", path_names: { new: "/" }
    resources :sessions, only: %i[new create destroy], path: "login", path_names: { new: "/" }
  end

  resources :users, only: %i[show], param: :username
  resources :categories, except: %i[show]
  resources :cars
  resources :favorites, only: %i[index create destroy], param: :car_id
  # Defines the root path route ("/")
  root "cars#index"
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :bigint           not null, primary key
#  registration :string           not null
#  brand        :string           not null
#  version      :string           not null
#  model        :string           not null
#  year         :integer          not null
#  color        :string           not null
#  price        :integer          not null
#  credit_price :integer
#  transmission :string           not null
#  traction     :string           not null
#  fuel         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :bigint
#
class Car < ApplicationRecord
  include PgSearch::Model
  include Favoritable
  pg_search_scope :whose_name_starts_with,
                  against: %i[brand model version],
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :registration, :brand, :version, :model, :color, :year, :price, :transmission,
            :traction, :fuel, presence: true

  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  has_one_attached :photo

  ORDER_BY = {
    newest: "created_at DESC",
    cheapest: "price ASC",
    expensive: "price DESC"
  }.freeze

  def owner?
    user_id == Current.user&.id
  end

  def broadcast
    broadcast_update_to self, target: "car_#{self.id}", partial: 'cars/car_details', locals: { car: self  }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :protect_pages, only: %i[index show]

  def index
    @categories = Category.order(name: :asc).load_async

    @pagy, @cars = pagy_countless(FindCars.new.call(car_params_index).load_async, items: 12)
  end

  def show
    car
  end

  def new
    @car = Car.new
  end

  def edit
    authorize! car
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = t(".created")
      redirect_to car_path(@car)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def update
    authorize! car
    if car.update(car_params)
      car.broadcast
      flash[:notice] = t(".edited")
      redirect_to car_path(car)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    authorize! car
    return unless car.destroy

    flash[:notice] = t(".deleted")
    redirect_to cars_path, status: :found
  end

  private

  def car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:registration, :brand, :version, :model, :year, :color, :price,
                                :transmission, :traction, :fuel, :photo, :category_id)
  end

  def car_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites,
                  :user_id)
  end


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div class="car bg-white mb-2 rounded sm:w-[calc(33.3333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)]">
  <div>
    <%= image_tag car.photo.attached? ? car.photo : 'placeholder.jpeg', class: "w-full h-60 object-cover" %>
  </div>
  <div class="m-2 flex justify-between">
    <div class="text-gray-500 text-sm">
      <p><%= car.brand %></p>
      <p><%= car.version %></p>
      <p><%= car.model %></p>
    </div>
    <div class="flex flex-col justify-between">
      <span class="font-bold text-xl">$<%= car.price %></span>
      <div class="text-gray-500 text-sm">
        <%= link_to t('.show_more'), car_path(car), data: { turbo_frame: '_top' } %>
        <%= link_to t('common.delete'), car_path(car), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') } if car.owner? %>
      </div>
    </div>
  </div>
</div>

app/views/cars/_car_details.html.erb
<div id="<%= dom_id(car)%>">
  <p class="registration"><%= car.registration %></p>
  <p class="brand"><%= car.brand %></p>
  <p class="version"><%= car.version %></p>
  <p class="model"><%= car.model %></p>
  <p class="year"><%= car.year %></p>
  <p class="color"><%= car.color %></p>
  <p class="price"><%= car.price %></p>
  <p class="transmission"><%= car.transmission %></p>
  <p class="traction"><%= car.traction %></p>
  <p class="fuel"><%= car.fuel %></p>
  <div class="">
    <%= image_tag(car.photo, width: 500) if car.photo.attached?  %>
  </div>
</div>

app/views/cars/_favorite.html.erb
<div id="favorite">
  <% if car.favorite%>
    <%= link_to "💔", favorite_path(car.id), data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to "💖", favorites_path(car_id: car.id), data: { turbo_method: :post } %>
  <% end %>
</div>

app/views/cars/_form.html.erb
  <%= form_with model: car do |form| %>
  <% car.errors.full_messages.each do |error| %>
    <div><%= error %></div>
  <% end %>
  <div>
    <%= form.text_field :registration, placeholder: t(".title_registration"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :brand, placeholder: t(".title_brand"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :version, placeholder: t(".title_version"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :model, placeholder: t(".title_model"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.number_field :year, placeholder: t(".title_year"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :color, placeholder: t(".title_color"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.number_field :price, placeholder: t(".title_price"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :transmission, placeholder: t(".title_transmission"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :traction, placeholder: t(".title_traction"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.text_field :fuel, placeholder: t(".title_fuel"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>
  <div>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name,{}, { class: "rounded-2xl border-gray-200 mb-4 w-full text-gray-500"} %>
  </div>
  <div>
    <%= form.label "Photos", class: " border-gray-200 mb-4 w-full text-gray-500" %>
    <%= form.file_field :photo, class: " border-gray-200 mb-4 w-full text-gray-500" %>
  </div>
  <div>
    <%= form.submit t(".create_car"), class: "px-4 py-2 font-semibold text-sm bg-cyan-500 text-white rounded-2xl cursor-pointer shadow-sm"  %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1><%=  t('.title') %></h1>
<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <%= form_with url: cars_path, class: "mx-1", method: :get do |form|%>
    <%= form.text_field :query_text , placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full my-2 rounded-2xl border-gray-200" %>
    <div class="flex">
      <%= form.number_field :min_price, placeholder: t('.min'), onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-2xl border-gray-200" %>
      <%= form.number_field :max_price, placeholder: t('.max'), onChange: 'this.form.requestSubmit()', value: params[:max_price],class: "w-1/3 rounded-2xl border-gray-200 mx-2" %>
      <%= form.select :order_by,  options_for_select(Car::ORDER_BY.keys.map { |key| [t(".#{key}"), key]}, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()',class: "w-1/3 rounded-2xl border-gray-200 text-gray-500"} %>
    </div>
  <% end %>
  <div class="flex overflow-x-scroll gap-2 m-2">
    <%= render(CategoryComponent.new) %>
    <%= render(CategoryComponent.with_collection(@categories)) %>
  </div>
  <%= turbo_frame_tag :cars do %>
    <%= turbo_frame_tag "cars-#{@pagy.page}", class: "cars flex flex-col px-2 w-full sm:flex-row sm:flex-wrap sm:gap-2" do %>
      <%= render partial: "car", collection: @cars %>
      <%= turbo_frame_tag "cars-#{@pagy.next}", class: "cars flex flex-col px-2 w-full sm:flex-row sm:flex-wrap sm:gap-2", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/cars/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p data-action="click->modal#close" class="mb-4">❌</p>
      <h1 class="font-bold mb-4"><%= t('.title') %></h1>
      <div>
        <%= render  "form", car: @car %>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/show.html.erb
<h1><%= t('.title')%></h1>
<div class="show">
  <%= render  partial: 'cars/car_details', locals: { car: @car } %>
  <%= link_to t('common.edit'), edit_car_path(@car) if @car.owner? %>
</div>
<%=link_to  t('.view_more_cars', username: @car.user.username), user_path(@car.user.username) %>
<%= render partial: 'favorite', locals: { car: @car } %>
<%= turbo_stream_from @car %>